### ISSUE TITLE
LineMap:CompareCurrent() C++ to Java 

### ISSUE THREAD

**Issue by codertimo** [codertimo/SideWalkDetection#11]
이것좀 바꿔주센
java에서는 Mat 생성을 Scalar혼자서는 안되는듯
Mat(int rows,int cols,Scalar s)는 있는거 같음

```cpp
//cpp 코드
smStack = Scalar(0);
```

```java
//java 코드
SWDUtil.smStack = new Mat(...)
```

**Comment by dmk98** [comment]
SWDUtil.smStack = new Mat(mLineMap.rows,mLineMap.cols,Scalar(0));

**Comment by codertimo** [comment]
Mat(int rows,int cols,OpenCVType type,Scalar s)
OpenCVType은 CV_xxxxx 이거 말하는듯 함

**Comment by dmk98** [comment]
CV_8U 
 사실 0임
