### ISSUE TITLE
[필수] 코드 수정작업

### ISSUE THREAD

**Issue by codertimo** [codertimo/SideWalkDetection#13]
**코드 마무리 작업**

C++코드를 Java로 전환하는 작업이 막바지에 접어들었습니다!
문제는 이게 정확하게 작동하는지가 문제인데, 바로 프로젝트를 돌리는것보다 모듈 하나하나 테스트 하는것이 좋을 듯합니당. 근데 동민이( @dmk98 ) 가 각 클래스랑 함수에 대한 설명을 안해줘서, 코드를 짜 놓고도, 이 함수가 뭐하는거지...?라는 생각이 듭니다. 논문이랑 같이 보려고 해도 뭐가 뭔지도 모르겠고 (좀 C++코드가 엉켜있다고 해야 할까..?)

**결론**

그래서 내가 짠 코드에다가 동민이( @dmk98 )가 주석을 달야야해! 그래야 내가 테스트를 진행하지(맨날 논문 쓰라고 뭐라하지말고 도와!) 그리고 **SWDUtils**에 들어가는 함수들이 정확하게 작성된건지 한번 코드 리뷰도 하고!

**요약**
내가 친절히 요약도 해주지...(글읽기 싫어하는 동민이에게)
1. 우선 코드 주석이 없어서 뭐가 뭔지 하나도 모르겠음 -> 내가 짠 Java코드에 주석을 달아라
2. 내가 짠 코드를 너가 한번 검사해 보아라 -> 코드 리뷰를 해서 결과를 올리도록
3. 해결되지 못한 Java->C++관련 Issue를 해결할 수 있도록 도와줘요! -> 이제 좀 마무리 합시다!
4. 1,2,3 번이 완료되면 내가 모듈별로 테스트를 진행할 것입니다.

**도움**
찬호형 (@utilForever )께서, 이에 대한 일정과 리드를 해주셨으면 합니다! 아무래도 저희 2명이서 프로젝트를 진행하다보니, 일정이나 프로젝트 진행이 원활하게 안되는 경향이...ㅎ 저랑 동민이 둘다 조금 (쪼아)주세요. 그래야 빨리 플젝을 끝내고 공부를 해야죠 ㅠㅠㅠㅠㅠㅠ 12월 이전까지는 완성되도록 하고 싶습니다. 논문 마무리 파트는 12월에 작성할 예정이고요.

**Comment by utilForever** [comment]
어떻게 리드해줬으면 좋겠나요~?

**Comment by codertimo** [comment]
일정에 관한 부분을 확실하게 마일스톤으로 만들어놓고 이를 실천할수있도록 리드해주세요!

**Comment by utilForever** [comment]
한 번 만나서 전체 일정을 잡는게 좋긴 한데 흠...

**Comment by codertimo** [comment]
만나기에는 시간이..... 어려울꺼 같은데....흠

**Comment by utilForever** [comment]
준성이랑 동민이는 각자의 영역에서 서로의 영역은 잘 안보는 것 같음.
준성이는 프로그램에는 많이 신경쓰고 있는데 논문을 많이 신경 못쓰는 것 같고,
동민이는 논문에는 많이 신경쓰고 있는데 프로그램에는 많이 신경 못쓰는 것 같음.
(오해할까봐 미리 이야기하는데 알고리즘을 짠 거랑은 별개의 문제임)

우선 동민이는 특히 알고리즘 부분에 상대방이 이해할 수 있도록 주석을 달아주는 작업을 해주고,
준성이는 논문을 읽어보고 다른 논문이랑 어떻게 결과를 비교할 것인지 생각해봤으면 해.

**Comment by codertimo** [comment]
네 알겠습니다. 확실히 논문에 신경쓰지 못했던것 같네요..
앞으로는 둘다 열심히 참여하도록 하겠습니다. 
논문은 이번주 내에 한번 다시 한번 읽어보고 피드백 드리도록 하겠습니다.
