### ISSUE TITLE
논문 폴더 정리

### ISSUE THREAD

**Issue by utilForever** [codertimo/SideWalkDetection#2]
Section 별로 논문을 작성할 수 있도록 파일을 분리할 예정.
Tex 폴더를 정리해서 올려줄테니 참고하기 바람.

**Comment by codertimo** [comment]
네 알겠습니다.

**Comment by codertimo** [comment]
올려주신 Latex 파일 어떤 구조로 되있고 각각의 파일이 어떤 역할하는지좀 설명해 주세요

**Comment by utilForever** [comment]
Readme.md 참고~
