### ISSUE TITLE
C++ to Java

### ISSUE THREAD

**Issue by codertimo** [codertimo/SideWalkDetection#4]
C++코드를 Android에 포팅하기 위해서 **C++ to Java** 작업을 실행하고 있음.
이에 대해서 현재 해야 할 사항들을 정리해봄

**현재 해야 할 사항**
1. C++의 완성적인 소스 커밋
2. 1번 작업을 기반으로 Java 코드로 기초 골격 잡기
3. C++개발자와 소스 리뷰 이후 수정
 
3번까지의 작업을 **2015/10/17** 까지 끝내야 한다고 생각합니다.

**Comment by dmk98** [comment]
조정해 보도록 하겠습니다 ^^

**Comment by dmk98** [comment]
소스 작업 끝나고요, 알고리즘 적용했습니다. 관련 설명 해드릴께요

**Comment by codertimo** [comment]
기본적으로 만들어놨으니, 코드에 주석좀 달아주센
**무조건!!!! 코드 한번 읽으면서, Java코드에 주석 달기!**

**Comment by codertimo** [comment]
+.... 제발 코드는.... 그렇게 쓰지 맙시다.

**Comment by dmk98** [comment]
?? 코드에 주석은 달아드리죠'
