### ISSUE TITLE
알고리즘 요약

### ISSUE THREAD

**Issue by dmk98** [codertimo/SideWalkDetection#5]
직선 전체에 대한 회귀 -> 손실 함수 작성 -> 서로 배타적인 직선(손실함수의 값 큰것) 선택 -> 치킨 먹기

**Comment by utilForever** [comment]
뭐죠, 치킨 먹기는

**Comment by codertimo** [comment]
치킨먹기는 벤하죠

**Comment by dmk98** [comment]
현재 프로그램 설정에서 알 수 없는 에러가 발생하여 스택 오버플로우가 계속되고 있습니다.
10월 21일까지 수정하도록 하겠습니다.
치킨은 그때 먹죠
