### ISSUE TITLE
result, conclusion

### ISSUE THREAD

**Issue by dmk98** [codertimo/SideWalkDetection#6]
주웅이가 요청 빨리 적당히 작업

**Comment by codertimo** [comment]
논문만쓰라고? 아님 코딩해서 코드로 결과 넘기고 정리하고 논문쓰는거?

**Comment by dmk98** [comment]
코딩해서 코드로 결과넘기고 정리하고 논문 쓰고 치킨 사주고, 집에서 재워줘
