### ISSUE TITLE
Vec4i to Java

### ISSUE THREAD

**Issue by codertimo** [codertimo/SideWalkDetection#7]
http://answers.opencv.org/question/23163/convert-vec4i-to-java/

코드를 짜다보니... Vec4i가 컨버팅이 안됨...? ㅎㅎㅎㅎ
MatOfInt4라는 객체를 이용하고 있는데 어떻게 할까요

**Comment by codertimo** [comment]
``` cpp
vector<Point>    : MatOfPoint
vector<Point2f>  : MatOfPoint2f
vector<Point3i>  : MatOfPoint3
vector<Point3f>  : MatOfPoint3f
vector<KeyPoint> : MatOfKeyPoint
vector<DMatch>   : MatOfDMatch
vector<Rect>     : MatOfRect
vector<uchar>    : MatOfByte
vector<char>     : MatOfByte
vector<int>      : MatOfInt
vector<float>    : MatOfFloat
vector<double>   : MatOfDouble
vector<Vec4i>    : MatOfInt4
vector<Vec4f>    : MatOfFloat4
vector<Vec6f>    : MatOfFloat6
```

**Comment by utilForever** [comment]
자문자답... ㅋㅋ

**Comment by codertimo** [comment]
MatOfint4 는 Mat 형태라 col, row값이 있는데 기존에는 vector<vec4i>.push_back()해서 넣어버렸으니....
이거 어떻게 변환해야 할지 좀 헬프좀;;;; (이거 모르겟으니깐 코드를 못짜겟네)

**Comment by codertimo** [comment]
@dmk98 빼에에에에에엑

**Comment by dmk98** [comment]
int[4] ㄱㄱ

**Comment by utilForever** [comment]
언어간에 호환성이 많이 안맞는 모양이군...

**Comment by codertimo** [comment]
Imgproc.HoughLinesP(thresholdImage, lines, 1, Math.PI/180, threshold, minLineSize, lineGap);

    for (int x = 0; x < lines.cols(); x++) 
    {
          double[] vec = lines.get(0, x);
          double x1 = vec[0], 
                 y1 = vec[1],
                 x2 = vec[2],
                 y2 = vec[3];
          Point start = new Point(x1, y1);
          Point end = new Point(x2, y2);

          Core.line(mRgba, start, end, new Scalar(255,0,0), 3);

    }

방법 찾았네 ;;; 컨버팅은 저런식으로 하면될듯

**Comment by utilForever** [comment]
역시 능력자 준성...
